// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CharacterItem: typeof import('./components/CharacterItem.vue')['default']
    CharactersList: typeof import('./components/CharactersList.vue')['default']
    ListTable: typeof import('./components/ListTable.vue')['default']
    Skeleton: typeof import('./components/Skeleton.vue')['default']
  }
}

export { }
